name: First Step to CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-lates, macOS-latest]
    steps:
      - name: Checkout the repo      
        uses: actions/checkout@v3     
      - name: Building container
        run: docker build -t my-apache2 .     
      - name: run Docker
        run: docker run -d -p 80:80 --name docker-apache -d my-apache2
      - name: check server
        run: curl http://localhost:80
      - name:  Install Google Chrome
        run:   |
                chmod +x ./scripts/InstallChrome.sh
                ./scripts/InstallChrome.sh 
      - name: Check out Selenium Script
        uses: actions/checkout@main
        with:
          repository: hermanka/SeleniumTry
          path: './SeleniumTry'
      - name: Show Working directory
        run: ls
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run Selenium Script
        run: |
              cd ./SeleniumTry
              mvn test
      - name : Stop Docker
        run : docker stop docker-apache



