# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation..

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo      
        uses: actions/checkout@v3
      - name: Show Working directory
        run: ls
      # - name: Publish AUT to Docker
      #   uses: addnab/docker-run-action@v3
      #   with:
      #     image: test-image:latest
      #     run: echo "hello world"
      # - name: pull Docker
      #   run: docker pull httpd
      # - name: check Docker
      #   run: docker images
      # - name: run Docker
      #   run: docker run -d -p 80:80 --name docker-apache -d httpd

      - name: Build container 
        uses: addnab/docker-run-action@v3
        with:
          image: httpd
          options: -v ${{ github.workspace }}:/usr/local/apache2/htdocs/
          run: |
                pwd
                ls -l /usr/local/apache2/htdocs/
      - name: run Docker
        run: docker run -d -p 80:80 --name docker-apache -d httpd
      - name: check server
        run: curl http://localhost:80 
      # - name:  Install Google Chrome # Using shell script to install Google Chrome
      #   run:   |
      #           chmod +x ./scripts/InstallChrome.sh
      #           ./scripts/InstallChrome.sh 
      # - name: Check out Selenium Script
      #   uses: actions/checkout@main
      #   with:
      #     repository: hermanka/SeleniumTry
      #     path: './SeleniumTry'
      # - name: Show Working directory
      #   run: ls
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      #     cache: maven
      # - name: Run Selenium Script
      #   run: |
      #         cd ./SeleniumTry
      #         mvn test
      # - name : Stop Docker
      #   run : docker stop docker-apache
    
    
   
